"""empty message

Revision ID: 382f6ad8b30f
Revises: 70f0fd5c351f
Create Date: 2022-08-20 09:32:16.133847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '382f6ad8b30f'
down_revision = '70f0fd5c351f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Show_venue_id_fkey', 'Show', type_='foreignkey')
    op.create_foreign_key(None, 'Show', 'Venue', ['venue_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.create_foreign_key('Show_venue_id_fkey', 'Show', 'Venue', ['venue_id'], ['id'])
    # ### end Alembic commands ###
