"""empty message

Revision ID: 70f0fd5c351f
Revises: 6bee76b55d17
Create Date: 2022-08-19 11:42:28.888113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70f0fd5c351f'
down_revision = '6bee76b55d17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Show',
                    sa.Column('artist_id', sa.Integer(), nullable=False),
                    sa.Column('venue_id', sa.Integer(), nullable=False),
                    sa.Column('start_time', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
                    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
                    sa.PrimaryKeyConstraint(
                        'artist_id', 'venue_id', 'start_time')
                    )
    op.add_column('Artist', sa.Column('website_link',
                  sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column(
        'seeking_venue', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('seeking_description',
                  sa.String(length=500), nullable=True))
    op.alter_column('Artist', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('Artist', 'city',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=False)
    op.alter_column('Artist', 'state',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=False)
    op.alter_column('Artist', 'genres',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=False)
    op.add_column('Venue', sa.Column(
        'genres', sa.String(length=120), nullable=False))
    op.add_column('Venue', sa.Column('website_link',
                  sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column(
        'seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('seeking_description',
                  sa.String(length=500), nullable=True))
    op.alter_column('Venue', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('Venue', 'city',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=False)
    op.alter_column('Venue', 'state',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=False)
    op.alter_column('Venue', 'address',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=False)
    op.create_unique_constraint(None, 'Venue', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'address',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=True)
    op.alter_column('Venue', 'state',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=True)
    op.alter_column('Venue', 'city',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=True)
    op.alter_column('Venue', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.drop_column('Venue', 'seeking_description')
    op.drop_column('Venue', 'seeking_talent')
    op.drop_column('Venue', 'website_link')
    op.drop_column('Venue', 'genres')
    op.drop_constraint(None, 'Artist', type_='unique')
    op.alter_column('Artist', 'genres',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=True)
    op.alter_column('Artist', 'state',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=True)
    op.alter_column('Artist', 'city',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=True)
    op.alter_column('Artist', 'name',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.drop_column('Artist', 'seeking_description')
    op.drop_column('Artist', 'seeking_venue')
    op.drop_column('Artist', 'website_link')
    op.drop_table('Show')
    # ### end Alembic commands ###
