"""empty message

Revision ID: bfd92ee98798
Revises: 382f6ad8b30f
Create Date: 2022-08-22 16:22:28.185906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfd92ee98798'
down_revision = '382f6ad8b30f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Artist', ['phone'])
    op.create_unique_constraint(None, 'Venue', ['phone'])
    op.alter_column('Artist', 'genres',
                    type_=sa.ARRAY(sa.String),
                    nullable=False)
    op.alter_column('Venue', 'genres',
                    type_=sa.ARRAY(sa.String),
                    nullable=False)
    op.create_check_constraint(
        None, 'Artist', "phone ~* '((?:\+\d{2}[-\.\s]??|\d{4}[-\.\s]??)?(?:\d{3}[-\.\s]??\d{3}[-\.\s]??\d{4}|\(\d{3}\)\s*\d{3}[-\.\s]??\d{4}|\d{3}[-\.\s]??\d{4}))'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue', type_='unique')
    op.drop_constraint(None, 'Artist', type_='unique')
    op.drop_constraint(None, 'Artist', type_='check')
    op.alter_column('Artist', 'genres',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('Venue', 'genres',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    # ### end Alembic commands ###
