"""empty message

Revision ID: e7ed560f258a
Revises: 535b69008758
Create Date: 2022-08-27 15:47:11.856363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7ed560f258a'
down_revision = '535b69008758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('category_id', sa.Integer(), nullable=False))
    op.drop_constraint('questions_category_fkey', 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'categories', ['category_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('questions', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('category', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key('questions_category_fkey', 'questions', 'categories', ['category'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('questions', 'category_id')
    # ### end Alembic commands ###
